export { default as Logo } from './logo.svg';
export { default as HomeIcon } from './home.svg';
export { default as CursorIcon } from './cursor.svg';
export { default as BookSaveIcon } from './book-save.svg';
export { default as ArrowLeftIcon } from './arrowLeft.svg';
export { default as ArrowRightIcon } from './arrowRight.svg';
export { default as MicrophoneIcon } from './microphone.svg';
export { default as MusicLibraryIcon } from './music-library.svg';
export { default as PlayIconDarkOpacity } from './playIconDarkOpacity.svg';
